
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  dockerId: 盟塔网络                                                                       # 阿里云 login username
  pwd: Mengta123                                                                          # 阿里云 login username
  namespace: mt_test                                                                      # 阿里云 命名空间
  imageName: test                                                                         # 阿里云 仓库名称
  registry: registry.cn-hangzhou.aliyuncs.com/mt_test/test                                # 阿里云 公网地址
  dockerfilepath:  samples/MicroserviceDemo/applications/AuthServer.Host/Dockerfile       # Github Dockerfile相对路径


steps:
- script: |
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: push to aliyun